language: python
python:
  - 2.7
  - 3.2
  - 3.4

env:
  - DJANGO='1.6'
  - DJANGO='1.7'

install:
  - if [[ $DJANGO == '1.6' ]]; then pip install django==1.6; fi
  - if [[ $DJANGO != '1.6' ]]; then pip install -e git+git://github.com/django/django.git@1.7c2#egg=django1.7rc2; fi
  - pip install django-markdown
  - pip install django-colorful
  - pip install git+git://github.com/bouttier/django-forms-bootstrap.git@master
  - pip install django-bootstrap3-datetimepicker
  - if [[ $DJANGO == '1.6' ]]; then pip install coveralls; fi

script:
  - if [[ $DJANGO == '1.6' ]]; then coverage run --branch --source=issue --omit=issue/migrations/*.py manage.py test; fi
  - if [[ $DJANGO != '1.6' ]]; then python manage.py test; fi

after_success:
  if [[ $DJANGO == '1.6' ]]; then coveralls; fi

notifications:
  irc:
    channels: "irc.freenode.org#ponytracker"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    skip_join: true
  email: false
