language: python
python:
  - 2.7
  - 3.4
  - 3.5

env:
  - DJANGO='1.8'
  - DJANGO_SETTINGS_MODULE='ponytracker.test_settings'

install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install coveralls; fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then coverage run --branch --source=accounts,permissions,tracker --omit=accounts/migrations/*.py,permissions/migrations/*.py,tracker/migrations/*.py,tracker/tasks.py manage.py test; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then python manage.py test; fi

after_success:
  if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then coveralls; fi

notifications:
  irc:
    channels: "irc.freenode.org#ponytracker"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    skip_join: true
  email: false
